Revert "fix(docker): Copy only cargo directory instead of full Rust installation"
This reverts commit ff635bf as it breaks Cargo analysis with:

```
error: rustup could not choose a version of cargo to run, because one
wasn't specified explicitly, and no default is configured.

help: run 'rustup default stable' to download the latest stable release of
Rust and set it as your default toolchain.
```

Signed-off-by: Sebastian Schuberth <sebastian@doubleopen.org>